server:
    error:
        whitelabel:
            enabled: false
<<<<<<< HEAD
    port: 90
    
=======
    port: 91

>>>>>>> 8f99a73e20ed6f1878032fe6d6e463fc430884d0
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: C##_bib404
    password: too115
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy:  org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
